main:
  experiment_name: "rinna_tweets_generation"
  train_twitter_id: "rikichannel1203"
  dataset_path: "data/processed/tweets"
  model_path: "models/"
  results_path: "results/"
  debug: True

training_args:
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  load_best_model_at_end: True
  evaluation_strategy: "steps"

prediction:
  do_sample: True
  top_p: 0.95
  top_k: 40
  temperature: 0.7
  repetition_penalty: 1.2
  num_return_sequences: 5

prediction_add:
  max_length: 100
  min_length: 10